# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12GxoJhxuhxaxDz9qKDp1FmbjKEi406Kb
"""

#Matris oluşturulması ve değerlerin girilmesi
a=3
b=3
matrix=[]
for i in range(a):
    c=[]
    for j in range(b):
        c.append(int(input()))
    matrix.append(c)
    
#Matrisin çıktısını veren kodlar
for i in range(a):
    for j in range(b):
        print(matrix[i][j],end=" ")
    print()